### ISSUE TITLE
Does "ng-disabled" work?

### ISSUE THREAD

**Issue by cmacdonnacha** [klarsys/angular-material-icons#55]
Hi,

Angular Material's "md-icon" supports a disabled look but it doesn't look like **ng-md-icons** does.

See [demo](http://codepen.io/cmacdonnacha/pen/wMOJYd).

I've set "ng-disabled="true" on the "md-button" directive but it doesn't make the icon look disabled.

A [fix](https://github.com/angular/material/commit/92aff331bd9397cc5469a70ca502dfc239239652) for this went into Angular Material's repo.

Thanks,
Cathal.

**Comment by dresslerit** [comment]
Should this button disappear (like visibility: hidden) or removed from the context (like display: none)?

**Comment by cmacdonnacha** [comment]
I would say it should be "greyed out". See the same [issue](https://github.com/angular/material/issues/2434) raised in the **md-icon** directive on angular material's project.

**Comment by urmilparikh** [comment]
A PR will help....

**Comment by patrickmichalina** [comment]
:+1:  Yea this is pretty needed... Anyone working on it?

**Comment by dresslerit** [comment]
Hi, I found an solution but I'd like to discuss which one of these we should use in our general css:

`/* Only if the element has the class .md-button and the option ng-disabled*`
`.md-button[disabled] ng-md-icon svg {`
`  fill: rgba(0, 0, 0, 0.26);`
`}*/`
`/* Only if the Element has ng-md-icon has ng-disabled*`
`ng-md-icon[disabled] svg {`
`  fill: rgba(0, 0, 0, 0.26);`
`}`
`*/`
`/*Every element that has an svg inside and has the tag ng-disabled*/`
`*[disabled] svg {`
`  fill: rgba(0, 0, 0, 0.26);`
`}`

My favorite is the last one, because I don't want to type for every element a rule. But it may have some unexpected reactions of other styles in your code. (I didn't test that.)

**Comment by urmilparikh** [comment]
I prefer the second method, will work only for ng-md-icon (or can make it work for md-icon as well).

**Comment by cmacdonnacha** [comment]
Yea I'd go with the second option as well to avoid unexpected behavior with other styles.
