### ISSUE TITLE
Relationship to $mdIconProvider?

### ISSUE THREAD

**Issue by brianfeister** [klarsys/angular-material-icons#9]
This library / directive looks really awesome - great work!  I'm curious if this was released before or after Angular Material and how the two interact?  It seems like the two are both valuable, while trying to do quite different things.  Also both seem relatively complex, I would imagine merging them into one would be difficult.  Thoughts?  Am I missing something?

**Comment by urmilparikh** [comment]
Thank you, Brian.
We developed this library during an older version of angular-material. We wanted some flexibility in color & size of icons and we didn't want to hand-pick .svg files when deploying for production. So, we wrapped all .svgs into a single file and this library came to existence.
angular-material has changed since then and there are many options now with md-icon directive.
Both libraries work differently but serve the same purpose, so they could potentially be merged.
